---
title: "week7"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

## R Markdown

員工的薪水分配，嚴重懷疑不是常態分配

100 : ->
/mu <- 100 #100個的平均值求/mu
/sd <- 100
/se(stander error) <- /sd/sqrt(100)

1.96

-1.96*/se，/mu，1.96*/se  #原始的常態分配

我們懷疑不是常態分配
採「boot strapping」 間接法
把我們得到的"100"個樣本，重複抽1000次，(每次必須抽"100"個)然後得到1000個平均(每次抽的數量要與樣本一樣!!)

在1000個平均值中找到mu，sd
  percentile(2.5), mu, persentile(97.5)  #得到的信賴區間


從1-300中抽樣本100個(產生索引號100個)
```{r}
N <-100
meta <- rnorm(N,5,2)  #全校有100個人
idx <- as.integer(runif(N)*N)+1  #條件:100個號碼中隨機抽100個，可以重複(重複抽樣)

#利用runif產生0~1的亂數100個，因為要產生1~100的數字，所以要將runif()*100，ex:(0~1)*100=0~100，產生出來會是0~99，所以要+1，變成0~100
hist(meta)

#meta[idx]    #動作:從meta中抽idx
smp <- meta[idx]  
 
s.sum <- summary(smp)
hist(smp)
s.mean <- s.sum[4]  #平均值mean
s.sd <- sd(smp)/sqrt(300)

#統計
print("sample mean")
print(s.mean) 
print("sample sd")
print(s.sd)

s.conf <- c(-1.96*s.sd, 1.96*s.sd)+s.mean
s.conf
```

```{r}
x <- seq(-4,4,length=100)
dy<- dnorm(x)
plot(x,dy,type="l",col="blue",lwd=2.5, lty="dotted",ylim=c(0,2))
#col顏色, lwd粗度, lty線條#plot是新增一張圖(開新視窗)

py <- pnorm(x)
lines(x,py,lty="dotted",col="red")  #lines是既有圖上新增
qy <- qnorm(x)
lines(x,qy,lty="solid",col="green")

```

```{r}
N <-100
metasample <- rnorm(N,5,2)  #全校有100個人
rndno <- as.integer(runif(N)*N)+1 
smp <- metasample[rndno]

hist(metasample,breaks = 50)

dd <- density(metasample) #density用來做資料探索
plot(dd)

#hist(metasample)

#lx <- seq(min(metasample), max(metasample), length=100)
#ly <- dnorm(lx, mean(metasample), sd(metasample))
#pnorm(lx)

#sy <- ly*N**diff(lx)[1]  #面積*density
#diff:後-前，diff(lx)[1]拿出lx的間隔
#lines(lx,sy)
```

##迴圈

```{r}
x <- 4
if(x>3){
  print("dd")
  
  } else {
  print("small")
}

#else要放在}後面
```
```{r}
x <- -4
if(x<0){
  print("Negative")
}else {
  print("Zero")
}
```
```{r}
x <- rnorm(10)
for(i in 1:10){
 print(x)
}
```
```{r}
N <-1000
metasample <- rnorm(N,5,2)  
bmu <- numeric(2000)  #給bmu1000個空位

for(i in 1:2000){
  rndno <- as.integer(runif(N)*N)+1 #每次抽100個號碼
  smp <- metasample[rndno] #其中1次
  bmu[i] <- mean(smp)
 
}

p <- density(bmu)
plot(p)
qq <- quantile(bmu)
qq
rug(qq, col="red")
```

```{r}
N <-1000
metasample <- rnorm(N,5,2)  
bmu <- numeric(1000)  #給bmu1000個空位

for(i in 1:1000){
  rndno <- as.integer(runif(N)*N)+1 #每次抽100個號碼
  smp <- metasample[rndno] #其中1次
  bmu[i] <- mean(smp)
 
}

p <- density(bmu)
plot(p)
qq <- quantile(bmu)
qq
rug(qq, col="red")
```

```{r}
N <-100
metasample <- rnorm(N,5,2)  
bmu <- numeric(1000)  #給bmu1000個空位

for(i in 1:1000){
  rndno <- as.integer(runif(N)*N)+1 #每次抽100個號碼
  smp <- metasample[rndno] #其中1次
  bmu[i] <- mean(smp)
 
}

p <- density(bmu)
plot(p)
qq <- quantile(bmu)
qq
rug(qq, col="red")
```

```{r}
N <-10
metasample <- rnorm(N,5,2)  
bmu <- numeric(1000)  #給bmu1000個空位

for(i in 1:1000){
  rndno <- as.integer(runif(N)*N)+1 #每次抽100個號碼
  smp <- metasample[rndno] #其中1次
  bmu[i] <- mean(smp)
 
}

p <- density(bmu)
plot(p)
qq <- quantile(bmu)
qq
rug(qq, col="red")

```


#結論:如何讓標準差往內縮? "樣本分配N會影響", numeric不會!















