---
title: "week6"
output: ''
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

## 邏輯值

x1 <- c(T,F)   #T,F,T,F...F會被切掉，剩下T,F,T
x2 <- c(F,T,T)
x1 | x2
x1 & x2

## 重複抽樣

A <- c("A", "B", "C", "D","F")
B <- A  #B=A
C <- c("A", "C", "C", "E")

A==C  #=>T,F,T,F =>1,0,1,0

A[c(1,1,1,1)] #A[]中括號內表示索引，我重複抽樣1號元素4次
A[c(1,3,3,2,1,2,3,1,2,3,4,1)] #重複抽樣4個元素


## which用法

which(A==C)

#什麼叫which?(從temp解釋)
temp <- 1:length(A)
temp[A==C]           #答案和直接用which(A==C)相同 #A等於C

temp[A!=C]          #A不等於C


temp <- 1:max(length(A),length(C))
temp[A!=C]

which(A!=C)

##10/22練習

0.題目:隨機產生1-300個號碼，共300個
```{r}
x <- as.integer(runif(300)*300)+1
```
#隨機產生1-300個號碼，共200個
#因為是0-299所以要+1得300，as.integer轉為整數
#x <- as.integer(runif(號碼中抽幾個)*產生的號碼)+1

##步驟
1.產生亂數300個，平均值=5，標準差=2的母體
```{r}
meta <- rnorm(300,5,2)
hist(meta)

x1 <- sort(meta)
plot(x1)
r1 <- rank(meta)
```

2.從1-300中抽樣本100個(產生索引號100個)
```{r}
meta <- rnorm(300,5,2)  #全校有300個人
idx <- as.integer(runif(100)*300)+1  #條件:300個號碼中隨機抽100號碼，可以重複

#利用runif產生0~1的亂數100個，因為要產生1~300的數字，所以要將runif()*300，ex:(0~1)*300=0~300

#meta[idx]    #動作:從meta中抽idx
s <- meta[idx]  
 
s.sum <- summary(s)
hist(s)
s.mean <- s.sum[4]  #平均值mean
s.sd <- sd(s)/sqrt(300)

#統計
print("sample mean")
print(s.mean) 
print("sample sd")
print(s.sd)

s.conf <- c(-1.96*s.sd, 1.96*s.sd)+s.mean
s.conf
```







